version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=kinesis,cloudformation,sts,s3,lambda,iam,apigateway    
    ports: 
      - '4566-4597:4566-4597'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
